# Generated by Django 3.1.3 on 2021-03-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=100)),
                ('lesson_2', models.CharField(max_length=100)),
                ('lesson_3', models.CharField(max_length=100)),
                ('lesson_4', models.CharField(max_length=100)),
                ('lesson_5', models.CharField(max_length=100)),
            ],
        ),
    ]
