# Generated by Django 3.1.3 on 2021-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210315_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=False, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
